### ISSUE TITLE
Policy

### ISSUE THREAD

**Issue by bpbastos** [edgardmessias/yii2-ibm-db2#10]
Olá @edgardmessias, estamos tentando rodar testes de aceitação usando seu driver para DB2 porém aparece a seguinte mensagem de erro:

  [yii\db\Exception] SQLSTATE[42704]: Undefined object: -204 [IBM][CLI Driver][DB2/LINUXX8664] SQL0204N  "DB2INST1.POLICY" is an undefined name.  SQLSTATE=42704
(SQLExecute[-204] at /PDO_IBM-1.3.4/ibm_statement.c:1136)
The SQL being executed was: SET INTEGRITY FOR "POLICY" ALL, "HMON_ATM_INFO" ALL, "HMON_COLLECTION" ALL, "academico_endereco" ALL,  "academico_feriado" ALL IMMEDIATE UNCHECKED;

Tem alguma dica?

**Comment by edgardmessias** [comment]
O que acontece se você executar esse SQL:
```sql
SET INTEGRITY FOR "POLICY" ALL, "HMON_ATM_INFO" ALL, "HMON_COLLECTION" ALL, "academico_endereco" ALL, "academico_feriado" ALL IMMEDIATE UNCHECKED;
```

Existem essas tabelas: POLICY, HMON_ATM_INFO, HMON_COLLECTION, academico_endereco, academico_feriado?

**Comment by bpbastos** [comment]
Executei e deu o mesmo erro: "DB2INST1.POLICY" is an undefined name. 

POLICY, HMON_ATM_INFO, HMON_COLLECTION não existem apenas as tabelas academico*

**Comment by edgardmessias** [comment]
Executa e coloque aqui o resultado: 

```sql
SELECT t.tabname FROM syscat.tables AS t WHERE t.type in ('T') AND t.ownertype != 'S'
```

**Comment by bpbastos** [comment]
OBS.: No primeiro erro eu omiti algumas tabelas.

Segue o resultado da consulta.
academico_endereco
academico_feriado
POLICY
HMON_ATM_INFO
HMON_COLLECTION

**Comment by edgardmessias** [comment]
Executa de novo, mas pegando todas colunas agora: 
```sql
SELECT * FROM syscat.tables AS t WHERE t.type in ('T') AND t.ownertype != 'S'
```

e tenta ver o que mais difere essas ultimas tabelas das outras.

**Comment by bpbastos** [comment]
Joguei no goodle drive para melhorar a visualização: https://docs.google.com/spreadsheets/d/1FudxvzTF4OGR1y-Dr9T8tt_VCSQPKIKFz5cquNYPnl0/edit#gid=0

Diferença que achei foi na primeira coluna "TABLESCHEMA" que muda de "DB2INST1" para "SYSTOOLS" no caso das tabelas HMON_ATM_INFO, HMON_COLLECTION, POLICY

**Comment by edgardmessias** [comment]
Veja se o commit que acabei de fazer resolve seu problema

**Comment by bpbastos** [comment]
Funcionou @edgardmessias, obrigado!

**Comment by edgardmessias** [comment]
Assim que der, vou gerar um novo release

**Comment by edgardmessias** [comment]
Gerei novo release.

Lembrando que não é totalmente compatível com as últimas versões do Yii2

**Comment by edgardmessias** [comment]
@bpbastos, me adiciona no skype se quiser conversar, meu nome vai estar igual ao github

**Comment by bpbastos** [comment]
Obrigado @edgardmessias! Sabe informar qual é a ultima versão do yii compativel com seu driver?
