### ISSUE TITLE
IBM driver does not support upsert statements using yii\web\DbSession

### ISSUE THREAD

**Issue by csears123** [edgardmessias/yii2-ibm-db2#11]
I have a recent clean download of Yii 2 basic app, and I configured the application component for 'session' to use yii\web\DbSession, similar to how we setup for Yii 1.1, and I received the error below.

"ibm does not support upsert statements."

Looking through the stack trace it appears the writeSession function in DbSession is now using the new upsert function (link below)

https://github.com/yiisoft/yii2/issues/13879
https://github.com/yiisoft/yii2/pull/15623

Can this support be added to the IBM DB2 driver?  It is a significant feature to be able to store session data in a database for our websites.

Thanks!

**Comment by csears123** [comment]
@edgardmessias were you able to get this driver/extension working with DbSession in Yii2?

**Comment by edgardmessias** [comment]
I need check

Em qua, 13 de mar de 2019 7:00 PM, Chris Sears <notifications@github.com>
escreveu:

**Comment by csears123** [comment]
@edgardmessias  have you had a chance to review this request?

**Comment by edgardmessias** [comment]
@csears123 , Sorry for my delay.
I'm busy in my work, but I will try to see it tomorrow.

**Comment by edgardmessias** [comment]
@csears123, there is support after `>= 1.4.0`
Could you attach the error message?
