### ISSUE TITLE
The extension 'pdo_ibm' is not provided by this buildpack.

### ISSUE THREAD

**Issue by umutc** [edgardmessias/yii2-ibm-db2#2]
Database Exception – yii\db\Exception

could not find driver
↵
Caused by: PDOException

could not find driver

in C:\www\htdocs\bluemix-yii2basic\vendor\yiisoft\yii2\db\Connection.php at line 600

**Comment by edgardmessias** [comment]
See this link: https://pecl.php.net/package/PDO_IBM

**Comment by umutc** [comment]
i downloaded "5.4 Non Thread Safe (NTS) x86" dll to my "C:\www\php\ext" folder.
from https://pecl.php.net/package/PDO_IBM/1.3.3/windows 
i uncommented this two lines
extension=php_pdo.dll
extension=php_pdo_ibm.dll

resatarted apache and not works

Connection settings for the SQL database
Host name   5.10.125.192
SSL port    50001
Database name   SQLDB
Version DB2LUW 10.5.4
SSL certificate strings
JDBC SSL String jdbc:db2://5.10.125.192:50001/SQLDB:securityMechanism=9
ODBC SSL DSN    DRIVER={IBM DB2 ODBC DRIVER};
DATABASE=SQLDB;
HOSTNAME=5.10.125.192;
PORT=50001;
PROTOCOL=TCPIP;
UID=<Your Username>;
PWD=<Your Password>;
Security=ssl;
SSLClientKeystoredb=<location of keystore>;
SSLClientKeystash=<location of stash file>;
Download the SSL certificate
Learn More about using SSL in your database client applications

**Comment by edgardmessias** [comment]
pdo_ibm is enabled in `phpinfo()` or `php -m`?
what version of your PHP?
restarted apache service?

**Comment by umutc** [comment]
phpinfo()
https://www.evernote.com/shard/s280/sh/1b1e6552-26af-4960-ad90-2a7740aee419/afa0cf8a2f2a12f7e6c3435e622baa3a

**Comment by umutc** [comment]
php -m
PDO_ODBC => yes
pdo_ibm       => no
hmm the problem is that i can not install this module (pdo_ibm)

**Comment by edgardmessias** [comment]
For PHP 5.6, you need compile PDO_IBM.
Alternatively, you can use ODBC: 
`odbc:DRIVER={IBM DB2 ODBC DRIVER};DATABASE=test;"HOSTNAME=127.0.0.1;PORT=50000;PROTOCOL=TCPIP`

**Comment by umutc** [comment]
odbc:DRIVER={IBM DB2 ODBC DRIVER};DATABASE=SQLDB;HOSTNAME=5.10.125.192;PORT=50001;PROTOCOL=TCPIP

[problem](https://www.evernote.com/shard/s280/sh/39476ba4-708d-472d-9ae8-9bfee7a9c898/52a3ee2966c168ae20f2f3a2dbad3c1e)
Setting unknown property: edgardmessias\db\ibm\db2\Connection::defaultSchema

**Comment by edgardmessias** [comment]
Update your yii2-ibm-db2 to 1.1.0

**Comment by umutc** [comment]
# updated 1.1.0

Database Exception – yii\db\Exception

↵
Caused by: PDOException

in C:\www\htdocs\bluemix-yii2basic\vendor\yiisoft\yii2\db\Connection.php at line 600

# 

'db' => [
            'class'         => 'edgardmessias\db\ibm\db2\Connection',
            'dsn'           => 'odbc:DRIVER={IBM DB2 ODBC DRIVER};DATABASE=SQLDB;HOSTNAME=5.10.125.192;PORT=50001;PROTOCOL=TCPIP',
            'username'      => 'name'
            'password'      => 'pw'
            'defaultSchema' => '',
            'isISeries'     => false
        ],

**Comment by edgardmessias** [comment]
Did you install the ODBC client 32-bit IBM DB2?

**Comment by umutc** [comment]
no i couldnt find it :(. i think that i wont be do that. i am going on myql.

**Comment by edgardmessias** [comment]
Try install DB2 Client and check in "C:\Windows\SysWOW64\odbcad32.exe"

**Comment by umutc** [comment]
# INSTALLED DRİVER

# odbc:DRIVER={IBM DB2 ODBC DRIVER};DATABASE=SQLDB;HOSTNAME=5.10.125.192;PORT=50001;PROTOCOL=TCPIP

Database Exception – yii\db\Exception

SQLSTATE[08001] SQLDriverConnect: -30081 [IBM][CLI Driver] SQL30081N A communication error has been detected. Communication protocol being used: "TCP/IP". Communication API being used: "SOCKETS". Location where the error was detected: "5.10.125.192". Communication function detecting the error: "recv". Protocol specific error code(s): "10054", "*", "0". SQLSTATE=08001
↵
Caused by: PDOException

SQLSTATE[08001] SQLDriverConnect: -30081 [IBM][CLI Driver] SQL30081N A communication error has been detected. Communication protocol being used: "TCP/IP". Communication API being used: "SOCKETS". Location where the error was detected: "5.10.125.192". Communication function detecting the error: "recv". Protocol specific error code(s): "10054", "*", "0". SQLSTATE=08001
in C:\www\htdocs\bluemix-yii2basic\vendor\yiisoft\yii2\db\Connection.php at line 600

**Comment by edgardmessias** [comment]
Try this: https://www-304.ibm.com/support/docview.wss?uid=swg21403644

**Comment by umutc** [comment]
I am sory and thank you for help. Problem fixed. It was a username/password problem in bluemix. I have'nt  saw this button :smile: 
![425dcb48-0d36-4638-a5d9-1f0c0132ae82](https://cloud.githubusercontent.com/assets/10675121/14002008/da66c5a6-f151-11e5-9257-1fdddb7119ac.jpg)
