### ISSUE TITLE
DB2 9.1

### ISSUE THREAD

**Issue by bpbastos** [edgardmessias/yii2-ibm-db2#4]
Hi @edgardmessias,

First I'd like to thank you for your work developing this extension. Thanks!

I'm working on a project that will use a old version of DB2, 9.1 + Fixpack 12 to be more especific. Do you know if your extension works with that version? If not, could you give me any hints in what changes would be necessary to make it work.

Thank you

**Comment by edgardmessias** [comment]
It's to be working with DB2(9.1).

If you have problem, open issues. I'll solve it when I can
