### ISSUE TITLE
Quoting incorreto

### ISSUE THREAD

**Issue by bpbastos** [edgardmessias/yii2-ibm-db2#7]
Oi @edgardmessias, estamos com o seguinte problema:

Em algumas consultas utilizamos os métodos joinWith (yii\db\ActiveQuery) e join (yii\db\Query) porém quando utilizamos o método join() a expressão da cláusula ON (e.horario_coordenador_id=h.id) não está ficando entre "quotes" e gera um erro no DB2 ao executar a consulta. 

**Exemplo:**

> Inscricao::find()
    ->joinWith(['candidato c'])
    ->joinWith(['entrevistas e'])
    ->join('INNER JOIN', 'inscricao_horario_coordenador h', 'e.horario_coordenador_id=h.id');

**Resultado:**

> SELECT "inscricao_inscricao".*
FROM "inscricao_inscricao"
LEFT JOIN "inscricao_candidato" "c" ON "inscricao_inscricao"."candidato_id" = "c"."id"
LEFT JOIN "inscricao_entrevista" "e" ON "inscricao_inscricao"."id" = "e"."inscricao_id"
INNER JOIN "inscricao_horario_coordenador" "h" ON e.horario_coordenador_id=h.id

**Comment by edgardmessias** [comment]
Olá @bpbastos, você pode testar isso:
 `->join('INNER JOIN', 'inscricao_horario_coordenador h', '{{e}}.[[horario_coordenador_id]]={{h}}.[[id]]')`

**Comment by edgardmessias** [comment]
@bpbastos , como você pode ver aqui: https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L1063

Se a condição não for `Expression` ou `array`, ele retorna do jeito que está.

Por isso que é sempre bom colocar `{{tabela}}` e `[[coluna]]` para comparar colunas.

Esse problema só ocorreu por causa do método `join`, que é instrução simples, e não faz parte do `ActiveRecord`.

**Comment by bpbastos** [comment]
Oi @edgardmessias desculpa a demora, usando o `Expression` como voce sugeriu resolveu o problema. Obrigado!
