### ISSUE TITLE
cant set DefaultSchema for connection string

### ISSUE THREAD

**Issue by btohir** [edgardmessias/yii2-ibm-db2#8]
Hello, 
My yii2 connection string to db2(ibm as400 iseries ) shown below:
'db' => [
            'class'         => 'edgardmessias\db\ibm\db2\Connection',
            'dsn'           => 'odbc:DRIVER={Client Access ODBC Driver (32-bit)}; SYSTEM=127.0.0.1; DATABASE="IASP01";PROTOCOL=TCPIP',
            'username'      => 'user',
            'password'      => 'pass',
            'defaultSchema' => 'MAINLIB',
            'isISeries'     => true
        ],

When I set defaultSchema occured following error:

SQLSTATE[42000]: Syntax error or access violation: -104 [IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0104 - Token <END-OF-STATEMENT> was not valid. Valid tokens: ? : USER DEFAULT SYSTEM_USER. (SQLExecDirect[-104] at ext\pdo_odbc\odbc_driver.c:247)
Error Info: Array
(
    [0] => 42000
    [1] => -104
    [2] => [IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0104 - Token <END-OF-STATEMENT> was not valid. Valid tokens: ? : USER DEFAULT SYSTEM_USER. (SQLExecDirect[-104] at ext\pdo_odbc\odbc_driver.c:247)
    [3] => 42000

Without defaultSchema I cant create  ActiveRecord model and controller.
if I write 'defaultSchema' => '', 
$temp = Yii::$app->db->createCommand('select * from mainlib.z')->queryAll(); 
query works fine.

**Comment by edgardmessias** [comment]
Full stack trace?

**Comment by btohir** [comment]
Database Exception – yii\db\Exception

SQLSTATE[42000]: Syntax error or access violation: -104 [IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0104 - Token <END-OF-STATEMENT> was not valid. Valid tokens: ? : USER DEFAULT SYSTEM_USER. (SQLExecDirect[-104] at ext\pdo_odbc\odbc_driver.c:247)
Error Info: Array
(
    [0] => 42000
    [1] => -104
    [2] => [IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0104 - Token <END-OF-STATEMENT> was not valid. Valid tokens: ? : USER DEFAULT SYSTEM_USER. (SQLExecDirect[-104] at ext\pdo_odbc\odbc_driver.c:247)
    [3] => 42000
)
↵
Caused by: PDOException

SQLSTATE[42000]: Syntax error or access violation: -104 [IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0104 - Token <END-OF-STATEMENT> was not valid. Valid tokens: ? : USER DEFAULT SYSTEM_USER. (SQLExecDirect[-104] at ext\pdo_odbc\odbc_driver.c:247)

in D:\xampp\htdocs\inventory\vendor\edgardmessias\yii2-ibm-db2\src\Connection.php at line 64
1. in D:\xampp\htdocs\inventory\vendor\yiisoft\yii2\db\Connection.php at line 597
588589590591592593594595596597598599600601602603604605606 
            if ($enableProfiling) {
                Yii::endProfile($token, __METHOD__);
            }
        } catch (\PDOException $e) {
            if ($enableProfiling) {
                Yii::endProfile($token, __METHOD__);
            }
 
            throw new Exception($e->getMessage(), $e->errorInfo, (int) $e->getCode(), $e);
        }
    }
 
    /**
     * Closes the currently active DB connection.
     * It does nothing if the connection is already closed.
     */
    public function close()
    {
2. in D:\xampp\htdocs\inventory\vendor\yiisoft\yii2\db\Connection.php at line 946 – yii\db\Connection::open()
3. in D:\xampp\htdocs\inventory\vendor\yiisoft\yii2\db\Connection.php at line 933 – yii\db\Connection::getMasterPdo()
4. in D:\xampp\htdocs\inventory\vendor\yiisoft\yii2\db\Command.php at line 243 – yii\db\Connection::getSlavePdo()
5. in D:\xampp\htdocs\inventory\vendor\yiisoft\yii2\db\Command.php at line 1066 – yii\db\Command::prepare(true)
6. in D:\xampp\htdocs\inventory\vendor\edgardmessias\yii2-ibm-db2\src\Command.php at line 32 – yii\db\Command::queryInternal('fetchAll', null)
26272829303132333435363738     * @throws yii\db\Exception if the query causes any problem
     * @since 2.0.1 this method is protected (was private before).
     */
    protected function queryInternal($method, $fetchMode = null)
    {
        if ($method !== '') {
            return parent::queryInternal($method, $fetchMode);
        }
 
        $rawSql = $this->getRawSql();
 
        Yii::info($rawSql, 'yii\db\Command::query');
 
7. in D:\xampp\htdocs\inventory\vendor\yiisoft\yii2\db\Command.php at line 390 – edgardmessias\db\ibm\db2\Command::queryInternal('fetchAll', null)
8. in D:\xampp\htdocs\inventory\controllers\SiteController.php at line 74 – yii\db\Command::queryAll()
68697071727374757677787980// get the row whose primary key is "US"
//$country = Country::findOne('US');
      //  $temp = Yii::$app->db->schema->getTableSchema('z');;
        //Yii::$app->db->createCommand("SET CURRENT SCHEMA MGOLIB")->queryAll();
        //  $temp = Yii::$app->db->schema;
        //Yii::$app->db->createCommand("SET CURRENT SCHEMA MGOLIB")->queryAll();
        $temp = Yii::$app->db->createCommand('select * from MGOLIB.z')->queryAll();
        echo "<pre>";
        print_r($temp);
        echo "</pre>";
        die;
 
        return $this->render('index');
9. app\controllers\SiteController::actionIndex()
10. in D:\xampp\htdocs\inventory\vendor\yiisoft\yii2\base\InlineAction.php at line 57 – call_user_func_array([app\controllers\SiteController, 'actionIndex'], [])
11. in D:\xampp\htdocs\inventory\vendor\yiisoft\yii2\base\Controller.php at line 157 – yii\base\InlineAction::runWithParams([])
12. in D:\xampp\htdocs\inventory\vendor\yiisoft\yii2\base\Module.php at line 528 – yii\base\Controller::runAction('', [])
13. in D:\xampp\htdocs\inventory\vendor\yiisoft\yii2\web\Application.php at line 103 – yii\base\Module::runAction('', [])
14. in D:\xampp\htdocs\inventory\vendor\yiisoft\yii2\base\Application.php at line 386 – yii\web\Application::handleRequest(yii\web\Request)
15. in D:\xampp\htdocs\inventory\web\index.php at line 12 – yii\base\Application::run()
6789101112 
require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/../vendor/yiisoft/yii2/Yii.php';
 
$config = require __DIR__ . '/../config/web.php';
 
(new yii\web\Application($config))->run();
 $_COOKIE = [
    '_identity' => '60a139dd346d23f52f0e8a1520ec56464bfbb26032af1d1037e0c83d2103dc78a:2:{i:0;s:9:"_identity";i:1;s:20:"[3,"123123",2592000]";}',
    'PHPSESSID' => '09107cbu18g1s1gutdesuf5tu5',
];

$_SESSION = [
    '__flash' => [],
];

**Comment by btohir** [comment]
<?php
namespace app\models;
use yii\db\ActiveRecord;
class G302ucpf extends ActiveRecord
{
    public static function tableName()
    {
        return 'MGOLIB.g302ucpf';
    }
}

**Comment by btohir** [comment]
<?php
namespace app\models;
use yii\db\ActiveRecord;
class G302ucpf extends ActiveRecord
{
    public static function tableName()
    {
        return 'MGOLIB.g302ucpf';
    }
}

**Comment by kenger** [comment]
Any news? I have the same problem with an AS400 iSeries

**Comment by edgardmessias** [comment]
Query example or stack?

**Comment by btohir** [comment]
@kenger , I can`t fix this issue. But I connected to AS400 with PDO connection, and working with query builder. I still cant create ActiveRecord model and controller.

**Comment by kenger** [comment]
Hi @edgardmessias, I attached the html page with the exception. I can also paste it here if you prefere.
[AS400 - Exception.zip](https://github.com/edgardmessias/yii2-ibm-db2/files/1667242/AS400.-.Exception.zip)

My config is
`[
            'class'         => 'edgardmessias\db\ibm\db2\Connection',
            'dsn'           => 'odbc:DRIVER={iSeries Access ODBC Driver};SYSTEM=IP;PROTOCOL=TCPIP',
            'username'      => 'USER',
            'password'      => 'PASS',
            'defaultSchema' => 'DEVDATA',
            'isISeries'     => true
        ]`

Checking @btohir config and mine, we both use a different driver from the doc, thats probably it. Both our ODBC drivers are from the AS400 installer and not from the IBM SDK. Is my assumption correct?

**Comment by edgardmessias** [comment]
I'll investigate

**Comment by edgardmessias** [comment]
Please, commet this line in your source and try again, please: https://github.com/edgardmessias/yii2-ibm-db2/blob/master/src/Connection.php#L77

**Comment by kenger** [comment]
Yes, without that line it works! Is that a problem with iSeries?

**Comment by edgardmessias** [comment]
Maybe is a problem with ODBC driver.

My source not has this query: `USER DEFAULT SYSTEM_USER`

**Comment by edgardmessias** [comment]
New release with fix "1.3.2".

**Comment by kenger** [comment]
Thanks for the rapid fix and for the library!

**Comment by edgardmessias** [comment]
@btohir , work for you?

**Comment by btohir** [comment]
Hello, I have following issue!

![image](https://user-images.githubusercontent.com/22738343/35797853-dd6e82b0-0a82-11e8-97e2-23c11360fd23.png)

![image](https://user-images.githubusercontent.com/22738343/35797998-5232fa36-0a83-11e8-840c-eb055e4fceb3.png)

![image](https://user-images.githubusercontent.com/22738343/35798103-9918c4a8-0a83-11e8-93e7-605035462b2e.png)

**Comment by edgardmessias** [comment]
@btohir, please, open new issue.

Try run manualy the SQL creation for migration.
