### ISSUE TITLE
Function sequence error in relation

### ISSUE THREAD

**Issue by kenger** [edgardmessias/yii2-ibm-db2#9]
Hi,

every time I use a relation on an AS400 i get the following exception:

`SQLSTATE[HY010]: Function sequence error: 0 [Microsoft][Driver Manager ODBC] Errore nella sequenza della funzione. (SQLExecute[0] at ext\pdo_odbc\odbc_stmt.c:254)
The SQL being executed was: SELECT * FROM "DEVDATA"."CNRIG00F" WHERE "CNRCOD"='123 '` .

Both this
`Yii::$app->db->createCommand('SELECT * FROM "DEVDATA"."CNRIG00F" WHERE "CNRCOD"=:val')
        ->bindValue(':val', '123 ')
        ->queryOne();`
and this
`ContrattoRighe::find()
            ->where(['CNRCOD'=>'123 '])->one();`

work, i have this problem only with the relation. 

The stacktrace is attached.
[Database Exception – yii_db_Exception.zip](https://github.com/edgardmessias/yii2-ibm-db2/files/1685784/Database.Exception.yii_db_Exception.zip)

**Comment by edgardmessias** [comment]
I believe the problem is in `queryOne ()`, Can you do the test without it?

**Comment by kenger** [comment]
I'm not sure what `queryOne()` are you talking about! I have the following code (with class renamed in english):

`$model = Master::find()->andWhere(['CNTCOD'=>'123'])->one();`
`print_r($model->details);`

where $model->details is a relation defined as

`return $this->hasMany(Detail::className(), ['CNRCOD' => 'CNTCOD']);`

`$model` is actually loaded, all data access works (thanks to yours awesome extension!) except for the relations!

So I'm not sure which queryOne should be removed!

**Comment by edgardmessias** [comment]
First, sorry, I got it wrong.

You can send structure of `CNRIG00F`?

Please, test:

Replace `'123 '` with six spaces at end


SQL EDITOR:
`SELECT * FROM "DEVDATA"."CNRIG00F" WHERE "CNRCOD"='123      '`

`Yii::$app->db->createCommand('SELECT * FROM "DEVDATA"."CNRIG00F" WHERE "CNRCOD"=:val')
        ->bindValue(':val', '123      ')
        ->queryOne();`

`ContrattoRighe::find()
            ->where(['CNRCOD'=>'123      '])->one();`

**Comment by kenger** [comment]
I tried running the sql in the exception manually in a sql program and using Yii2 DAO in any possible way and that works flawlessly. The relation is used and mantained by Yii so i cant change anything involved directly.

The problem is with ALL the relations, i have multiple table related and all relations have the same problem. The only thing in common is the type of the foreign key column, a CHAR. Maybe I can try with a DECIMAL column. If you still need it i can send the structure of CNRIG00F.

**Comment by edgardmessias** [comment]
Please, try with decimal.

Send the data type for Primary key and foreing key.

**Comment by kenger** [comment]
I just double checked... all table have the primary key set as CHAR(9) and the foreign key set as CHAR(6). Making the length consistent solved my issue.

**Comment by edgardmessias** [comment]
Great.

**Comment by kenger** [comment]
Thanks for the help and sorry for the wasted time!
